apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::078083578991:role/testing_nodes-eks-node-group-20260316121114733000000002
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::078083578991:role/jenkins-devops-role
      username: jenkins-admin
      groups:
        - system:masters